import { Noto_Sans, Poppins } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans({
  subsets: ["latin"], // Specify the subset
  weight: ["400", "700"], // Choose font weights
  variable: "--font-noto", // Optional: Define a CSS variable
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Add desired weights
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
